package cat.editor.view.cell;

/**
 *
 * @author pavel.koupil
 */
public enum CellType {

	CATEGORICAL_OBJECT,
	MAPPING_KIND,
	MAPPING_PROPERTY,
	MAPPING_SELECTED_KIND,
	MAPPING_SELECTED_PROPERTY,
	MAPPING_NAME,
	MAPPING_AVAILABLE,
	MAPPING_AVAILABLE_PROPERTY,
	MAPPING_AVAILABLE_KIND,
	MAPPING_AVAILABLE_NAME,
	MAPPING_SELECTED_NAME,
	ER_ENTITY,
	ER_RELATIONSHIP,
	ER_ATTRIBUTE,
	ER_IDENTIFIER,
	ER_WEAK_IDENTIFIER,
	SELECTED,
	POSTGRESQL_KIND,
	MONGODB_KIND

}
