services:
    adminer:
        container_name: "mmcat-adminer"
        restart: always
        build:
            context: .
            dockerfile: docker/adminer/Dockerfile
        ports:
            - ${ADMINER_PORT}:8080

    database:
        container_name: "mmcat-database"
        restart: always
        build:
            context: .
            dockerfile: docker/database/Dockerfile
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRESQL_SUPERUSER_PASSWORD}
        expose:
            - 5432

    postgresql:
        container_name: "mmcat-postgresql"
        restart: always
        build:
            context: .
            dockerfile: docker/postgresql/Dockerfile
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRESQL_SUPERUSER_PASSWORD}
        expose:
            - 5432

    mongodb:
        container_name: "mmcat-mongodb"
        restart: always
        build:
            context: .
            dockerfile: docker/mongodb/Dockerfile
        env_file: .env
        expose:
            - 27017

    neo4j:
        container_name: "mmcat-neo4j"
        restart: always
        build:
            context: .
            dockerfile: docker/neo4j/Dockerfile
        env_file: .env
        environment:
            - NEO4J_AUTH=neo4j/${EXAMPLE_PASSWORD}
        expose:
            - 7473
            - 7474
            - 7687

networks:
    default:
        name: mmcat-network
