version: '3'

services:
    adminer:
        container_name: "mmcat-adminer"
        restart: always
        build: 
            context: .
            dockerfile: docker/adminer/Dockerfile
        ports:
            - ${ADMINER_PORT}:8080

    postgresql:
        container_name: "mmcat-postgresql"
        restart: always
        build: 
            context: .
            dockerfile: docker/postgresql/Dockerfile
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRESQL_SUPERUSER_PASSWORD}
        expose:
            - 5432
        ports:
            # Make the DB available on localhost for development.
            - ${POSTGRESQL_PORT}:5432

    mongodb:
        container_name: "mmcat-mongodb"
        restart: always
        build: 
            context: .
            dockerfile: docker/mongodb/Dockerfile
        env_file: .env
        expose:
            - 27017
        ports:
            # Make the DB available on localhost for development.
            - ${MONGODB_PORT}:27017

    neo4j:
        container_name: "mmcat-neo4j"
        restart: always
        build: 
            context: .
            dockerfile: docker/neo4j/Dockerfile
        env_file: .env
        environment:
            - NEO4J_AUTH=neo4j/${DB_EXAMPLE_PASSWORD}
        expose:
            - 7473 # This one is for https, which can be ignored on localhost
            - 7474
            - 7687
        ports:
            # Make the DB available on localhost for development.
            - ${MM_NEO4J_PORT}:7687
            # The bolt port has to be as is because the browser client expects it to be there.
            - ${MM_NEO4J_BROWSER_PORT}:7474

networks:
    default:
        name: mmcat-network
