services:
    server:
        container_name: "mmcat-server"
        restart: always
        build:
            context: library
            dockerfile: docker/prod/Dockerfile
            args:
                serverPort: ${SERVER_PORT}
                serverOrigin: ${CLIENT_DOMAIN}
                databasePassword: ${DATABASE_PASSWORD}
        expose:
            - "${SERVER_PORT}"
        volumes:
            - .uploads:/app/uploads

    client:
        container_name: "mmcat-client"
        restart: always
        build:
            # Sets source directory for all COPY, ADD, etc. commands in the Dockerfile
            context: client
            # Path to the dockerfile
            dockerfile: docker/prod/Dockerfile
        ports:
            # Map localhost port to 80 in docker
            - ${CLIENT_PORT}:80

networks:
    default:
        name: mmcat-network
        external: true
