#!/bin/bash

# psql postgresql://${EXAMPLE_USERNAME}:${EXAMPLE_PASSWORD}@localhost:${EXAMPLE_PORT}/${EXAMPLE_DATABASE_BASIC} -f src/main/resources/setupPostgresqlBasic.sql

psql --username postgres << EOSQL
SET ROLE postgres;
CREATE ROLE "${EXAMPLE_USERNAME}" LOGIN PASSWORD '${EXAMPLE_PASSWORD}';
CREATE DATABASE "${EXAMPLE_DATABASE_BASIC}" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "${EXAMPLE_DATABASE_ADMINER}" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "${EXAMPLE_DATABASE_QUERY_EVOLUTION}" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "${BENCHMARK_DATABASE_YELP}" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "${BENCHMARK_DATABASE_CALDOTCOM}" OWNER "${EXAMPLE_USERNAME}";

CREATE DATABASE "test" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "querying-a" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "querying-b" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "querying-c" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "querying-d" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "querying-e" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "querying-f" OWNER "${EXAMPLE_USERNAME}";

\c "${EXAMPLE_DATABASE_BASIC}";
SET ROLE "${EXAMPLE_USERNAME}";
\i setupPostgresqlBasic.sql;

\c "${EXAMPLE_DATABASE_ADMINER}";
SET ROLE "${EXAMPLE_USERNAME}";
\i setupPostgresqlAdminer.sql;

\c "${EXAMPLE_DATABASE_QUERY_EVOLUTION}";
SET ROLE "${EXAMPLE_USERNAME}";
\i setupPostgresqlQueryEvolution.sql;
EOSQL
