#!/bin/bash

# psql postgresql://${EXAMPLE_USERNAME}:${EXAMPLE_PASSWORD}@localhost:${EXAMPLE_PORT}/${EXAMPLE_DATABASE} -f src/main/resources/createExample.sql

psql --username postgres << EOSQL
SET ROLE postgres;
CREATE ROLE "${EXAMPLE_USERNAME}" LOGIN PASSWORD '${EXAMPLE_PASSWORD}';
CREATE DATABASE "${EXAMPLE_DATABASE}" OWNER "${EXAMPLE_USERNAME}";
CREATE DATABASE "test" OWNER "${EXAMPLE_USERNAME}";

\c "${EXAMPLE_DATABASE}";
SET ROLE "${EXAMPLE_USERNAME}";
\i createExample.sql;
EOSQL
