baseURL: 'https://mmcatdb.com/'
title: MM-cat docs
theme: hugo-geekdoc
defaultContentLanguage: en
languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 10

pluralizeListTitles: false
pygmentsUseClasses: true
pygmentsCodeFences: true
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
taxonomies:
  tag: tags
params:
  custom_css:
    - css/custom.css
