package cz.cuni.matfyz.editor.model;

/**
 *
 * @author pavel.koupil
 */
public enum EdgeType {
	CATEGORICAL,
// 	INCOMPLETE_CATEGORICAL,	// TODO - PRIDANO NAVIC, ZAHOD
// 	CRITICAL_CATEGORICAL,	// TODO - PRIDANO NAVIC, ZAHOD
	AVAILABLE_CATEGORICAL,
	SELECTED_CATEGORICAL,
	PROPERTY_CATEGORICAL,
	PROPERTY_NONBASE_CATEGORICAL,
	PROPERTY_INCOMPLETE_CATEGORICAL,
	NAME_CATEGORICAL,
	ER
}
