package cat.editor.view.edge;

/**
 *
 * @author pavel.koupil
 */
public enum EdgeType {
	CATEGORICAL,
	AVAILABLE_CATEGORICAL,
	SELECTED_CATEGORICAL,
	PROPERTY_CATEGORICAL,
	PROPERTY_NONBASE_CATEGORICAL,
	PROPERTY_INCOMPLETE_CATEGORICAL,
	NAME_CATEGORICAL,
	ER
}
