stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/gitlab-ci-utils/docker-hugo:latest
  variables:
    SITE: '$CI_PROJECT_DIR/site'
    DEST: '$CI_PROJECT_DIR/public'
  artifacts:
    paths:
    - public
  script:
    - hugo --cleanDestinationDir --source $SITE --destination $DEST

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
