stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/gitlab-ci-utils/docker-hugo:latest
  artifacts:
    paths:
    - public
  script:
    - hugo --cleanDestinationDir

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y lftp
    - lftp -e "set ssl:verify-certificate no; open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -I .htaccess -X .*/ --reverse --verbose ./public/ .; bye"



