stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/gitlab-ci-utils/docker-hugo:latest
  artifacts:
    paths:
    - public
  script:
    - hugo --cleanDestinationDir

deploy:
  stage: deploy
  # image: byteflair/ssh-rsync
  image: ubuntu:latest
  script:
    - echo $FTP_PASSWORD
    - echo $FTP_USERNAME
    - echo $FTP_HOST
    - apt install -y sshpass
    - apt install -y rsync
    - apt install -y ssh
    - sshpass -p "$FTP_PASSWORD" rsync -e 'ssh -p 42222' --delete -r public/. $FTP_USERNAME@$FTP_HOST:/var/www/html/mmcat-docs



