stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/gitlab-ci-utils/docker-hugo:latest
  artifacts:
    paths:
    - public
  script:
    - hugo --cleanDestinationDir

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
