stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/gitlab-ci-utils/docker-hugo:latest
  artifacts:
    paths:
    - public
  script:
    - hugo --cleanDestinationDir

deploy:
  stage: deploy
  image: eeacms/rsync
  script:
    - apt-get update -qy
    - apt-get install -y lftp
    - sshpass -p "$FTP_PASSWORD" rsync -e 'ssh -p 42222' --delete -r public/. $FTP_USERNAME@$FTP_HOST:/var/www/html/mmcat-docs



